;============================================================;
;                                                            ;
;                                                            ;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗   ;
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗  ;
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝  ;
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗  ;
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║  ;
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝  ;
;                                                            ;
;                                                            ;
;   To learn more about how to configure Polybar             ;
;   go to https://github.com/polybar/polybar                 ;
;                                                            ;
;   The README contains a lot of information                 ;
;                                                            ;
;============================================================;

[colors]
background = #FD161320
foreground = #CCC3BAC6
transparent = #00000000

[bar/i3polybar]
width = 100%
height = 27
;offset-x = 1%
;offset-y = 1%
radius = 0
; fixed-center = false

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0

bottom = true

border-size = 0

padding-left = 1
padding-right = 0

module-margin = 2
; module-padding = 5
; module-margin-left = 1
; module-margin-right = 1
module-margin-bottom = 0

font-0 = "Font Awesome 5 Free Solid:style=Solid;3"
font-1 = "Font Awesome 5 Free Regular:style=Regular;3"
font-2 = "Font Awesome 5 Brands Regular:style=Regular;3"
font-3 = "NotoSansMono Nerd Font;3"

modules-left = i3
; modules-center =
modules-right = ping temperature2 temperature1 temperature0 cpu memory battery backlight date

tray-position = right
tray-padding = 3

scroll-up = "#i3.prev"
scroll-down = "#i3.next"

cursor-click = pointer

; separator = │

monitor = ${env:MONITOR:}

[module/i3]
type = internal/i3

pin-workspaces = true

index-sort = true

fuzzy-match = true

ws-icon-0  = 0 ;  
ws-icon-1  = 1 ;
ws-icon-2  = 2 ;
ws-icon-3  = 3 ;
ws-icon-4  = 4 ;
ws-icon-5  = 5 ;
ws-icon-6  = 6 ;
ws-icon-7  = 7 ;
ws-icon-8  = 8 ;
ws-icon-9  = 9 ;
ws-icon-10 = 10 ;

format = <label-state><label-mode>

label-focused = %icon% %index% 
label-unfocused = %index%
label-urgent = %icon% %index%
label-visible = %icon% %index%

label-focused-foreground = #161320
label-focused-background = #B5E8E0
; label-unfocused-foreground = ${colors.foreground}
label-urgent-foreground = #161320
label-urgent-background = #F28FAD

label-focused-underline = #B5E8E0
; label-unfocused-underline = ${colors.foreground}
label-urgent-underline = #F28FAD
label-visible-underline = ${colors.foreground}

label-focused-padding = 2
label-unfocused-padding = 1
label-urgent-padding = 2
label-visible-padding = 2

; label-separator = │

; label-mode = %{F#10A778}│%{F-}%mode%
label-mode-underline = #FAE3B0
label-mode-foreground = #161320
label-mode-background = #FAE3B0
label-mode-padding = 4

[module/date]
type = internal/date
interval = 1

date = %a %d/%m,

time = %T

format = <label>
format-underline = #F5E0DC

label = %{B#F5E0DC}%{F#161320}  %{F-}%{B-} %date% %time%

[module/backlight]
type = internal/backlight

card = acpi_video1

enable-scroll = true

format = <ramp> <label>
label = %percentage%%

ramp-0 = "%{B#92A7Ce}%{F#161320}  %{F-}%{B-}%{F#92A7Ce}"
ramp-1 = "%{B#A4B5D6}%{F#161320}  %{F-}%{B-}%{F#A4B5D6}"
ramp-2 = "%{B#B6C3DE}%{F#161320}  %{F-}%{B-}%{F#B6C3DE}"
ramp-3 = "%{B#C7D2E6}%{F#161320}  %{F-}%{B-}%{F#C7D2E6}"
ramp-4 = "%{B#D9D0EE}%{F#161320}  %{F-}%{B-}%{F#D9D0EE}"
ramp-5 = "%{B#EBEEF6}%{F#161320}  %{F-}%{B-}%{F#EBEEF6}"
ramp-6 = "%{B#FCFDFE}%{F#161320}  %{F-}%{B-}%{F#FCFDFE}"

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
full-at = 100

poll-interval = 3

format-charging = <animation-charging> <label-charging>
format-charging-underline = #F2CDCD
label-charging = %percentage%%↑

format-discharging =  <ramp-capacity> <label-discharging>
label-discharging = %percentage%%↓

format-full = <ramp-capacity> <label-full>
format-full-underline = #F5E0DC
label-full = %percentage%%

ramp-capacity-0 = "%{B#E8A2AF}%{F#161320}  %{B-}%{F-}%{F#E8A2AF}"
ramp-capacity-1 = "%{B#F8BD96}%{F#161320}  %{B-}%{F-}%{F#F8BD96}"
ramp-capacity-2 = "%{B#FAE3B0}%{F#161320}  %{B-}%{F-}%{F#FAE3B0}"
ramp-capacity-3 = "%{B#ABE9B3}%{F#161320}  %{B-}%{F-}%{F#ABE9B3}"
ramp-capacity-4 = "%{B#B5E8E0}%{F#161320}  %{B-}%{F-}%{F#B5E8E0}"
ramp-capacity-5 = "%{B#D9E0EE}%{F#161320}  %{B-}%{F-}%{F#D9E0EE}"
ramp-capacity-6 = "%{B#F5E0DC}%{F#161320}  %{B-}%{F-}%{F#F5E0DC}"

animation-charging-0 =  "%{B#F2CDCD}%{F#161320}   %{B-}%{F-}%{F#F2CDCD}"
animation-charging-1 =  "%{B#F2CDCD}%{F#161320}   %{B-}%{F-}%{F#F2CDCD}"
animation-charging-2 =  "%{B#F2CDCD}%{F#00000000} %{B#F2CDCD}%{F#161320}  %{B-}%{F-}%{F#F2CDCD}"
animation-charging-3 =  "%{B#F2CDCD}%{F#00000000} %{B#F2CDCD}%{F#161320}  %{B-}%{F-}%{F#F2CDCD}"
animation-charging-4 =  "%{B#F2CDCD}%{F#161320}   %{B-}%{F-}%{F#F2CDCD}"
animation-charging-5 =  "%{B#F2CDCD}%{F#161320}   %{B-}%{F-}%{F#F2CDCD}"
animation-charging-6 =  "%{B#F2CDCD}%{F#00000000} %{B#F2CDCD}%{F#161320}  %{B-}%{F-}%{F#F2CDCD}"
animation-charging-7 =  "%{B#F2CDCD}%{F#00000000} %{B#F2CDCD}%{F#161320}  %{B-}%{F-}%{F#F2CDCD}"
animation-charging-8 =  "%{B#F2CDCD}%{F#161320}   %{B-}%{F-}%{F#F2CDCD}"
animation-charging-9 =  "%{B#F2CDCD}%{F#161320}   %{B-}%{F-}%{F#F2CDCD}"
animation-charging-10 = "%{B#F2CDCD}%{F#00000000} %{B#F2CDCD}%{F#161320}  %{B-}%{F-}%{F#F2CDCD}"
animation-charging-11 = "%{B#F2CDCD}%{F#00000000} %{B#F2CDCD}%{F#161320}  %{B-}%{F-}%{F#F2CDCD}"
animation-charging-12 = "%{B#F2CDCD}%{F#161320}   %{B-}%{F-}%{F#F2CDCD}"
animation-charging-13 = "%{B#F2CDCD}%{F#161320}   %{B-}%{F-}%{F#F2CDCD}"
animation-charging-14 = "%{B#F2CDCD}%{F#00000000} %{B#F2CDCD}%{F#161320}  %{B-}%{F-}%{F#F2CDCD}"
animation-charging-15 = "%{B#F2CDCD}%{F#00000000} %{B#F2CDCD}%{F#161320}  %{B-}%{F-}%{F#F2CDCD}"
animation-charging-16 = "%{B#F2CDCD}%{F#161320}   %{B-}%{F-}%{F#F2CDCD}"
animation-charging-17 = "%{B#F2CDCD}%{F#161320}   %{B-}%{F-}%{F#F2CDCD}"
animation-charging-18 = "%{B#F2CDCD}%{F#00000000} %{B#F2CDCD}%{F#161320}  %{B-}%{F-}%{F#F2CDCD}"
animation-charging-19 = "%{B#F2CDCD}%{F#00000000} %{B#F2CDCD}%{F#161320}  %{B-}%{F-}%{F#F2CDCD}"
animation-charging-framerate = 400

[module/memory]
type = internal/memory
interval = 3
format = <ramp-used> <label>
label = %percentage_used%%
ramp-used-6 = "%{B#E8A2AF}%{F#161320}  %{B-}%{F-}%{F#E8A2AF}"
ramp-used-5 = "%{B#F8BD96}%{F#161320}  %{B-}%{F-}%{F#F8BD96}"
ramp-used-4 = "%{B#FAE3B0}%{F#161320}  %{B-}%{F-}%{F#FAE3B0}"
ramp-used-3 = "%{B#ABE9B3}%{F#161320}  %{B-}%{F-}%{F#ABE9B3}"
ramp-used-2 = "%{B#B5E8E0}%{F#161320}  %{B-}%{F-}%{F#B5E8E0}"
ramp-used-1 = "%{B#D9E0EE}%{F#161320}  %{B-}%{F-}%{F#D9E0EE}"
ramp-used-0 = "%{B#F5E0DC}%{F#161320}  %{B-}%{F-}%{F#F5E0DC}"

[module/cpu]
type = internal/cpu
interval = 2

format = <ramp-load> <label> <ramp-coreload>
; format = <ramp-load> <label>

label = %percentage%%

ramp-coreload-spacing = 0
ramp-coreload-0 = "%{F#F5E0DC}▁"
ramp-coreload-1 = "%{F#D9E0EE}▂"
ramp-coreload-2 = "%{F#B5E8E0}▃"
ramp-coreload-3 = "%{F#ABE9B3}▄"
ramp-coreload-4 = "%{F#FAE3B0}▅"
ramp-coreload-5 = "%{F#F8BD96}▆"
ramp-coreload-6 = "%{F#E8A2AF}▇"
ramp-coreload-7 = "%{F#F28FAD}█"

ramp-load-0 = "%{B#F5E0DC}%{F#161320}  %{B-}%{F-}%{F#F5E0DC}"
ramp-load-1 = "%{B#D9E0EE}%{F#161320}  %{B-}%{F-}%{F#D9E0EE}"
ramp-load-2 = "%{B#B5E8E0}%{F#161320}  %{B-}%{F-}%{F#B5E8E0}"
ramp-load-3 = "%{B#ABE9B3}%{F#161320}  %{B-}%{F-}%{F#ABE9B3}"
ramp-load-4 = "%{B#FAE3B0}%{F#161320}  %{B-}%{F-}%{F#FAE3B0}"
ramp-load-5 = "%{B#F8BD96}%{F#161320}  %{B-}%{F-}%{F#F8BD96}"
ramp-load-6 = "%{B#E8A2AF}%{F#161320}  %{B-}%{F-}%{F#E8A2AF}"
ramp-load-7 = "%{B#F28FAD}%{F#161320}  %{B-}%{F-}%{F#F28FAD}"

[module/temperature0]
type = internal/temperature
interval = 2
thermal-zone = 0
base-temperature = 20
warn-temperature = 60
format = <ramp> <label>
format-warn = <label-warn>
label = %temperature-c%
label-warn = %{B#F28FAD}%{F#161320}  %{B-}%{F-}%{F#F28FAD} %temperature-c%%{F-}
ramp-6 = "%{B#E8A2AF}%{F#161320}  %{B-}%{F-}%{F#E8A2AF}"
ramp-5 = "%{B#F8BD96}%{F#161320}  %{B-}%{F-}%{F#F8BD96}"
ramp-4 = "%{B#FAE3B0}%{F#161320}  %{B-}%{F-}%{F#FAE3B0}"
ramp-3 = "%{B#ABE9B3}%{F#161320}  %{B-}%{F-}%{F#ABE9B3}"
ramp-2 = "%{B#B5E8E0}%{F#161320}  %{B-}%{F-}%{F#B5E8E0}"
ramp-1 = "%{B#D9E0EE}%{F#161320}  %{B-}%{F-}%{F#D9E0EE}"
ramp-0 = "%{B#F5E0DC}%{F#161320}  %{B-}%{F-}%{F#F5E0DC}"
[module/temperature1]
type = internal/temperature
interval = 2
; thermal-zone = 4
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon9/temp1_input
base-temperature = 20
warn-temperature = 60
format = <ramp> <label>
format-warn = <label-warn>
label = %temperature-c%
label-warn = %{B#F28FAD}%{F#161320}    %{B-}%{F-}%{F#F28FAD} %temperature-c%%{F-}
ramp-6 = "%{B#E8A2AF}%{F#161320}   %{B-}%{F-}%{F#E8A2AF}"
ramp-5 = "%{B#F8BD96}%{F#161320}   %{B-}%{F-}%{F#F8BD96}"
ramp-4 = "%{B#FAE3B0}%{F#161320}   %{B-}%{F-}%{F#FAE3B0}"
ramp-3 = "%{B#ABE9B3}%{F#161320}   %{B-}%{F-}%{F#ABE9B3}"
ramp-2 = "%{B#B5E8E0}%{F#161320}   %{B-}%{F-}%{F#B5E8E0}"
ramp-1 = "%{B#D9E0EE}%{F#161320}   %{B-}%{F-}%{F#D9E0EE}"
ramp-0 = "%{B#F5E0DC}%{F#161320}   %{B-}%{F-}%{F#F5E0DC}"
[module/temperature2]
type = internal/temperature
interval = 2
; thermal-zone = 4
hwmon-path = /sys/devices/pci0000:00/0000:00:1d.4/0000:09:00.0/nvme/nvme1/hwmon3/temp1_input
base-temperature = 20
warn-temperature = 60
format = <ramp> <label>
format-warn = <label-warn>
label = %temperature-c%
label-warn = %{B#F28FAD}%{F#161320}    %{B-}%{F-}%{F#F28FAD} %temperature-c%%{F-}
ramp-6 = "%{B#E8A2AF}%{F#161320}   %{B-}%{F-}%{F#E8A2AF}"
ramp-5 = "%{B#F8BD96}%{F#161320}   %{B-}%{F-}%{F#F8BD96}"
ramp-4 = "%{B#FAE3B0}%{F#161320}   %{B-}%{F-}%{F#FAE3B0}"
ramp-3 = "%{B#ABE9B3}%{F#161320}   %{B-}%{F-}%{F#ABE9B3}"
ramp-2 = "%{B#B5E8E0}%{F#161320}   %{B-}%{F-}%{F#B5E8E0}"
ramp-1 = "%{B#D9E0EE}%{F#161320}   %{B-}%{F-}%{F#D9E0EE}"
ramp-0 = "%{B#F5E0DC}%{F#161320}   %{B-}%{F-}%{F#F5E0DC}"

[module/ping]
type = custom/script
exec = perl /home/vale/.i3polybarscripts/pingDataPolyBar && /home/vale/.i3polybarscripts/ipAndVpnData.sh
interval = 5

[settings]
screenchange-reload = true

[global/wm]
margin-top = 5
margin-bottom = 5

[module/tray]
type = internal/tray
tray-size = 100%
format-margin = 8px
tray-spacing = 8px
